default: &default

  # Basic
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  census_url: <%= ENV['CENSUS_URL'] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  sidekiq_web_usr: <%= ENV["SIDEKIQ_WEB_USR"] %>
  sidekiq_web_pwd: <%= ENV["SIDEKIQ_WEB_PWD"] %>

  # Omniauth
  omniauth:
    facebook:
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: true
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: true
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>

  # Geocoding
  geocoder:
    here_app_id: <%= ENV["HERE_APP_ID"] %>
    here_app_code: <%= ENV["HERE_APP_CODE"] %>

  # SMTP
  email: ENV["EMAIL"]
  sendgrid: <%= ENV["SENDGRID_ACCOUNT"] %>
  smtp_username: <%= ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
