test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  access_key_id: <%= Rails.application.secrets.storage.dig(:s3, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.storage.dig(:s3, :secret_access_key) %>
  region: <%= Rails.application.secrets.storage.dig(:s3, :region) %>
  bucket: <%= Rails.application.secrets.storage.dig(:s3, :bucket) %>

